
col_explode_1 = "team"
col_explode_2 = "team_cards"
col_explode_3 = "opponent"
col_explode_4 = "opponent_cards"


columns_explode_team = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "opponent",
    "raw_file_name",
]


columns_explode_opponent = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "team",
    "raw_file_name",
]




columns_explode_team_cards = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "team_crowns",
    "team_kingTowerHitPoints",
    "team_name",
    "team_princessTowersHitPoints",
    "team_startingTrophies",
    "team_tag",
    "team_trophyChange",
    "team_clan_badgeId",
    "team_clan_name",
    "team_clan_tag",
    "opponent",
    "raw_file_name",
]

columns_explode_opponent_cards = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "opponent_crowns",
    "opponent_kingTowerHitPoints",
    "opponent_name",
    "opponent_princessTowersHitPoints",
    "opponent_startingTrophies",
    "opponent_tag",
    "opponent_trophyChange",
    "opponent_clan_badgeId",
    "opponent_clan_name",
    "opponent_clan_tag",
    "raw_file_name",
]




columns_team_final = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "team_crowns",
    "team_kingTowerHitPoints",
    "team_name",
    "team_startingTrophies",
    "team_tag",
    "team_trophyChange",
    "team_clan_badgeId",
    "team_clan_name",
    "team_clan_tag",
    "team_princessTowersHitPoints_1",
    "team_princessTowersHitPoints_2",
    "team_cards_id",
    "team_cards_level",
    "team_cards_maxLevel",
    "team_cards_name",
    "team_cards_starLevel",
    "team_cards_iconUrls_medium",
    "raw_file_name",
]

columns_opponent_final = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "opponent_crowns",
    "opponent_kingTowerHitPoints",
    "opponent_name",
    "opponent_startingTrophies",
    "opponent_tag",
    "opponent_trophyChange",
    "opponent_clan_badgeId",
    "opponent_clan_name",
    "opponent_clan_tag",
    "opponent_princessTowersHitPoints_1",
    "opponent_princessTowersHitPoints_2",
    "opponent_cards_id",
    "opponent_cards_level",
    "opponent_cards_maxLevel",
    "opponent_cards_name",
    "opponent_cards_starLevel",
    "opponent_cards_iconUrls_medium",
    "raw_file_name",
]

columns_opponent_final_only_diferente_columns= [
    "opponent_crowns",
    "opponent_kingTowerHitPoints",
    "opponent_name",
    "opponent_startingTrophies",
    "opponent_tag",
    "opponent_trophyChange",
    "opponent_clan_badgeId",
    "opponent_clan_name",
    "opponent_clan_tag",
    "opponent_princessTowersHitPoints_1",
    "opponent_princessTowersHitPoints_2",
    "opponent_cards_id",
    "opponent_cards_level",
    "opponent_cards_maxLevel",
    "opponent_cards_name",
    "opponent_cards_starLevel",
    "opponent_cards_iconUrls_medium",
]



columns_7 = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "team_crowns",
    "team_kingTowerHitPoints",
    "team_name",
    "team_princessTowersHitPoints_1",
    "team_princessTowersHitPoints_2",
    "team_startingTrophies",
    "team_tag",
    "team_trophyChange",
    "team_clan_badgeId",
    "team_clan_name",
    "team_clan_tag",
    "team_cards_id",
    "team_cards_level",
    "team_cards_maxLevel",
    "team_cards_name",
    "team_cards_starLevel",
    "team_cards_iconUrls_medium",
    "opponent_crowns",
    "opponent_kingTowerHitPoints",
    "opponent_name",
    "opponent_startingTrophies",
    "opponent_tag",
    "opponent_trophyChange",
    "opponent_clan_badgeId",
    "opponent_clan_name",
    "opponent_clan_tag",
    "opponent_princessTowersHitPoints",
    "raw_file_name",
]

columns_9 = [
    "battleTime",
    "boatBattleSide",
    "boatBattleWon",
    "deckSelection",
    "isHostedMatch",
    "isLadderTournament",
    "newTowersDestroyed",
    "prevTowersDestroyed",
    "remainingTowers",
    "type",
    "gameMode_id",
    "gameMode_name",
    "arena_id",
    "arena_name",
    "team_crowns",
    "team_kingTowerHitPoints",
    "team_name",
    "team_princessTowersHitPoints_1",
    "team_princessTowersHitPoints_2",
    "team_startingTrophies",
    "team_tag",
    "team_trophyChange",
    "team_clan_badgeId",
    "team_clan_name",
    "team_clan_tag",
    "team_cards_id",
    "team_cards_level",
    "team_cards_maxLevel",
    "team_cards_name",
    "team_cards_starLevel",
    "team_cards_iconUrls_medium",
    "opponent_crowns",
    "opponent_kingTowerHitPoints",
    "opponent_name",
    "opponent_princessTowersHitPoints_1",
    "opponent_princessTowersHitPoints_2",
    "opponent_startingTrophies",
    "opponent_tag",
    "opponent_trophyChange",
    "opponent_clan_badgeId",
    "opponent_clan_name",
    "opponent_clan_tag",
    "opponent_cards_id",
    "opponent_cards_level",
    "opponent_cards_maxLevel",
    "opponent_cards_name",
    "opponent_cards_starLevel",
    "opponent_cards_iconUrls_medium",
    "raw_file_name",
]